/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.EntidadesBanco.Compra;
import Entidade.EntidadesBanco.Despesa;
import Entidade.EntidadesBanco.Venda;
import Interfaces.TemplateLista;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author r4f4s
 */
public class Analize extends javax.swing.JFrame {
    private Class classe;
    /**
     * Creates new form Analize
     */
    public Analize() {
        initComponents();
        classe = Venda.class;
        try {
            tl= (TemplateLista) classe.newInstance();//cria instacia //porque precisa do (templatelista)
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Listagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        atualizaTabela();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTanalizeVenda = new javax.swing.JButton();
        BTanalizeCompra = new javax.swing.JButton();
        BTanalizeDespesa = new javax.swing.JButton();
        BTanalizeFinanceira = new javax.swing.JButton();
        LBfiltros = new javax.swing.JLabel();
        LBdataInicial = new javax.swing.JLabel();
        LBdataFinal = new javax.swing.JLabel();
        LBcodigo = new javax.swing.JLabel();
        SPdadosAnalize = new javax.swing.JScrollPane();
        JTanalize = new javax.swing.JTable();
        LBtotais = new javax.swing.JLabel();
        LBvalor = new javax.swing.JLabel();
        LBquantidadeRegistros = new javax.swing.JLabel();
        TFcodigo = new javax.swing.JTextField();
        FTFdataFinal = new javax.swing.JFormattedTextField();
        FTFdataInicial = new javax.swing.JFormattedTextField();
        TFquantidadeRegistros = new javax.swing.JTextField();
        TFvalor = new javax.swing.JTextField();
        BTaplicarFiltros = new javax.swing.JButton();
        BTsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTanalizeVenda.setBackground(new java.awt.Color(204, 255, 255));
        BTanalizeVenda.setForeground(new java.awt.Color(0, 0, 0));
        BTanalizeVenda.setText("Analize de VENDAS");
        BTanalizeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanalizeVendaActionPerformed(evt);
            }
        });

        BTanalizeCompra.setBackground(new java.awt.Color(204, 255, 255));
        BTanalizeCompra.setForeground(new java.awt.Color(0, 0, 0));
        BTanalizeCompra.setText("Analize de COMPRAS");
        BTanalizeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanalizeCompraActionPerformed(evt);
            }
        });

        BTanalizeDespesa.setBackground(new java.awt.Color(204, 255, 255));
        BTanalizeDespesa.setForeground(new java.awt.Color(0, 0, 0));
        BTanalizeDespesa.setText("Analize de DESPESAS");
        BTanalizeDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanalizeDespesaActionPerformed(evt);
            }
        });

        BTanalizeFinanceira.setBackground(new java.awt.Color(204, 255, 255));
        BTanalizeFinanceira.setForeground(new java.awt.Color(0, 0, 0));
        BTanalizeFinanceira.setText("Analize FINANCEIRA");
        BTanalizeFinanceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanalizeFinanceiraActionPerformed(evt);
            }
        });

        LBfiltros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBfiltros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBfiltros.setText("Filtros:");

        LBdataInicial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdataInicial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBdataInicial.setText("Data Inicial:");

        LBdataFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdataFinal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBdataFinal.setText("Data FInal:");

        LBcodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBcodigo.setText("Codigo:");

        JTanalize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPdadosAnalize.setViewportView(JTanalize);

        LBtotais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBtotais.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBtotais.setText("Totais:");

        LBvalor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBvalor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBvalor.setText("Valor:");

        LBquantidadeRegistros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBquantidadeRegistros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBquantidadeRegistros.setText("Quantidade de Registros:");

        FTFdataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        FTFdataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        BTaplicarFiltros.setBackground(new java.awt.Color(153, 255, 153));
        BTaplicarFiltros.setForeground(new java.awt.Color(0, 0, 0));
        BTaplicarFiltros.setText("Aplicar FIltros");

        BTsair.setBackground(new java.awt.Color(255, 86, 86));
        BTsair.setForeground(new java.awt.Color(0, 0, 0));
        BTsair.setText("Sair");
        BTsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBquantidadeRegistros)
                                .addGap(18, 18, 18)
                                .addComponent(TFquantidadeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBvalor)
                                .addGap(18, 18, 18)
                                .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LBtotais))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SPdadosAnalize, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BTanalizeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBcodigo)
                                                .addGap(18, 18, 18)
                                                .addComponent(TFcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BTanalizeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTanalizeDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTanalizeFinanceira, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBdataInicial)
                                                .addGap(18, 18, 18)
                                                .addComponent(FTFdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(LBdataFinal)
                                                .addGap(18, 18, 18)
                                                .addComponent(FTFdataFinal))))
                                    .addComponent(LBfiltros))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BTaplicarFiltros)
                                        .addGap(115, 115, 115))
                                    .addComponent(BTsair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTanalizeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTanalizeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTanalizeDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTanalizeFinanceira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTsair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBfiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBdataInicial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LBcodigo)
                                .addComponent(TFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FTFdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LBdataFinal)
                                .addComponent(FTFdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(BTaplicarFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPdadosAnalize, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBtotais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBquantidadeRegistros)
                        .addComponent(LBvalor)
                        .addComponent(TFquantidadeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTanalizeDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTanalizeDespesaActionPerformed
        try {
            tl= (TemplateLista) Despesa.class.newInstance();//cria instacia //porque precisa do (templatelista)
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Listagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizaTabela();
    }//GEN-LAST:event_BTanalizeDespesaActionPerformed

    private void BTanalizeFinanceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTanalizeFinanceiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTanalizeFinanceiraActionPerformed

    private void BTanalizeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTanalizeVendaActionPerformed
        try {
            tl= (TemplateLista) Venda.class.newInstance();//cria instacia //porque precisa do (templatelista)
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Listagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizaTabela();
    }//GEN-LAST:event_BTanalizeVendaActionPerformed

    private void BTanalizeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTanalizeCompraActionPerformed
        try {
            tl= (TemplateLista) Compra.class.newInstance();//cria instacia //porque precisa do (templatelista)
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Listagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizaTabela();
    }//GEN-LAST:event_BTanalizeCompraActionPerformed

    private void BTsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsairActionPerformed
        dispose();
    }//GEN-LAST:event_BTsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTanalizeCompra;
    private javax.swing.JButton BTanalizeDespesa;
    private javax.swing.JButton BTanalizeFinanceira;
    private javax.swing.JButton BTanalizeVenda;
    private javax.swing.JButton BTaplicarFiltros;
    private javax.swing.JButton BTsair;
    private javax.swing.JFormattedTextField FTFdataFinal;
    private javax.swing.JFormattedTextField FTFdataInicial;
    private javax.swing.JTable JTanalize;
    private javax.swing.JLabel LBcodigo;
    private javax.swing.JLabel LBdataFinal;
    private javax.swing.JLabel LBdataInicial;
    private javax.swing.JLabel LBfiltros;
    private javax.swing.JLabel LBquantidadeRegistros;
    private javax.swing.JLabel LBtotais;
    private javax.swing.JLabel LBvalor;
    private javax.swing.JScrollPane SPdadosAnalize;
    private javax.swing.JTextField TFcodigo;
    private javax.swing.JTextField TFquantidadeRegistros;
    private javax.swing.JTextField TFvalor;
    // End of variables declaration//GEN-END:variables
    private List<TemplateLista> lista;
    private TemplateLista tl;
    
    private void atualizaTabela() {
        //lista = DAO.listaNative(classe);
   
        Object[][] dados= new Object[6][tl.getTitulos().length];
        /*
        for (int i = 0; i < lista.size(); i++) {
            dados[i]=lista.get(i).getDados();
        }
        */
        JTanalize.setModel(new DefaultTableModel(dados,tl.getTitulos()));
    }
}
