/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.DAO;
import Entidade.EntidadesBanco.Login;
import java.awt.Color;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class TLogin extends javax.swing.JFrame {
    DAO dao = new DAO();
    /**
     * Creates new form Login
     */
    public TLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBlogin = new javax.swing.JLabel();
        TFusuario1 = new javax.swing.JTextField();
        PFsenha = new javax.swing.JPasswordField();
        BTentrar = new javax.swing.JButton();
        BTsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBlogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LBlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBlogin.setText("Login");

        TFusuario1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFusuario1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFusuario1.setText("Usuário");
        TFusuario1.setToolTipText("");
        TFusuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFusuario1MouseClicked(evt);
            }
        });

        PFsenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PFsenha.setText("Senha");
        PFsenha.setToolTipText("Senha");
        PFsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PFsenhaMouseClicked(evt);
            }
        });

        BTentrar.setBackground(new java.awt.Color(153, 255, 255));
        BTentrar.setForeground(new java.awt.Color(0, 0, 0));
        BTentrar.setText("Entrar");
        BTentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTentrarActionPerformed(evt);
            }
        });

        BTsair.setBackground(new java.awt.Color(247, 87, 87));
        BTsair.setForeground(new java.awt.Color(0, 0, 0));
        BTsair.setText("Sair");
        BTsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(LBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(BTentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(412, 423, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTsair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BTsair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(LBlogin)
                .addGap(73, 73, 73)
                .addComponent(TFusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(PFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTentrarActionPerformed
        List listalogin = new LinkedList();
        listalogin = DAO.listaNative(Login.class);
        Login login = new Login();
        boolean ver = false;
        for (Object loginlista : listalogin) {
            login = (Login) loginlista;
            if(login.getUsuario().equals(TFusuario1.getText()) && login.getSenha().equals(String.valueOf(PFsenha.getPassword()))){
               ver = true; 
            }
        }
        if (ver == true){
            new Principal().setVisible(true);
            dispose();
        } else {
             JOptionPane.showMessageDialog(null, "Usuario e/ou senha incorretos!!");
        }
    }//GEN-LAST:event_BTentrarActionPerformed

    private void BTsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_BTsairActionPerformed

    private void TFusuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFusuario1MouseClicked
        TFusuario1.setText("");
    }//GEN-LAST:event_TFusuario1MouseClicked

    private void PFsenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PFsenhaMouseClicked
        PFsenha.setText("");
    }//GEN-LAST:event_PFsenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        UIManager.put( "control", new Color( 255, 229, 106) );
        UIManager.put( "info", new Color(255, 229, 106) );
        UIManager.put( "nimbusBase", new Color( 255, 214, 106) );
        UIManager.put( "nimbusAlertYellow", new Color( 248, 187, 0) );
        UIManager.put( "nimbusDisabledText", new Color( 128, 128, 128) );
        UIManager.put( "nimbusFocus", new Color(115,164,209) );
        UIManager.put( "nimbusInfoBlue", new Color( 66, 139, 221) );
        UIManager.put( "nimbusLightBackground", new Color(255, 214, 106) );
        UIManager.put( "nimbusOrange", new Color(191,98,4) );
        UIManager.put( "nimbusRed", new Color(169,46,34) );
        UIManager.put( "nimbusSelectedText", new Color( 38, 32, 16) );
        UIManager.put( "nimbusSelectionBackground", new Color( 255, 236, 148) );
        UIManager.put("nimbusBlueGrey", new Color(255, 214, 106));
        UIManager.put( "text", new Color( 38, 32, 16) );
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(TLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTentrar;
    private javax.swing.JButton BTsair;
    private javax.swing.JLabel LBlogin;
    private javax.swing.JPasswordField PFsenha;
    private javax.swing.JTextField TFusuario1;
    // End of variables declaration//GEN-END:variables
}
