/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Interfaces.TemplateLista;
import Interfaces.TemplatePainelCadastro;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author r4f4s
 */
public class VendaCompra extends javax.swing.JDialog {

    private TemplatePainelCadastro painelVendaCompra;
    private TemplatePainelCadastro painelItem;
    
    /**
     * Creates new form VendaCompra
     * @param parent
     * @param modal
     * @param painelVendaCompra
     * @param painelItem
     */
    public VendaCompra(java.awt.Frame parent, boolean modal,TemplatePainelCadastro painelVendaCompra,TemplatePainelCadastro painelItem) {
        super(parent, modal);
        this.painelVendaCompra = painelVendaCompra;
        this.painelItem = painelItem;
        initComponents();
        JPvendaCompra.add(painelVendaCompra,BorderLayout.CENTER);
        JPitem.add(painelItem,BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPvendaCompra = new javax.swing.JPanel();
        JPitem = new javax.swing.JPanel();
        BTsair = new javax.swing.JButton();
        BTsalvar = new javax.swing.JButton();
        BTcancelar = new javax.swing.JButton();
        BTsalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPvendaCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout JPvendaCompraLayout = new javax.swing.GroupLayout(JPvendaCompra);
        JPvendaCompra.setLayout(JPvendaCompraLayout);
        JPvendaCompraLayout.setHorizontalGroup(
            JPvendaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPvendaCompraLayout.setVerticalGroup(
            JPvendaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        JPitem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout JPitemLayout = new javax.swing.GroupLayout(JPitem);
        JPitem.setLayout(JPitemLayout);
        JPitemLayout.setHorizontalGroup(
            JPitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        JPitemLayout.setVerticalGroup(
            JPitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        BTsair.setBackground(new java.awt.Color(255, 86, 86));
        BTsair.setForeground(new java.awt.Color(0, 0, 0));
        BTsair.setText("Sair");
        BTsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsairActionPerformed(evt);
            }
        });

        BTsalvar.setBackground(new java.awt.Color(204, 255, 204));
        BTsalvar.setForeground(new java.awt.Color(0, 0, 0));
        BTsalvar.setText("Salvar");

        BTcancelar.setBackground(new java.awt.Color(255, 255, 204));
        BTcancelar.setForeground(new java.awt.Color(0, 0, 0));
        BTcancelar.setText("Cancelar");

        BTsalvar1.setBackground(new java.awt.Color(204, 255, 255));
        BTsalvar1.setForeground(new java.awt.Color(0, 0, 0));
        BTsalvar1.setText("Adicionar");
        BTsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPitem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPvendaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTsair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTsalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTcancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTsalvar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BTsair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPvendaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JPitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(BTsalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsairActionPerformed
        dispose();
    }//GEN-LAST:event_BTsairActionPerformed

    private void BTsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTsalvar1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTcancelar;
    private javax.swing.JButton BTsair;
    private javax.swing.JButton BTsalvar;
    private javax.swing.JButton BTsalvar1;
    private javax.swing.JPanel JPitem;
    private javax.swing.JPanel JPvendaCompra;
    // End of variables declaration//GEN-END:variables
}
