/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Entidade.EntidadesBanco.Cargo;
import Interfaces.TemplatePainelCadastro;

/**
 *
 * @author r4f4s
 */
public class CadastroCargo extends TemplatePainelCadastro {

    /**
     * Creates new form CadastroCargo
     */
    public CadastroCargo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBnomeCargo = new javax.swing.JLabel();
        LBsalario = new javax.swing.JLabel();
        TFnomeCargo = new javax.swing.JTextField();
        TFsalario = new javax.swing.JTextField();

        LBnomeCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBnomeCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBnomeCargo.setText("Nome do Cargo:");

        LBsalario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBsalario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBsalario.setText("Salário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TFsalario))
                    .addComponent(TFnomeCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBnomeCargo))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(LBnomeCargo)
                .addGap(18, 18, 18)
                .addComponent(TFnomeCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBsalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBnomeCargo;
    private javax.swing.JLabel LBsalario;
    private javax.swing.JTextField TFnomeCargo;
    private javax.swing.JTextField TFsalario;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        Cargo c = new Cargo();
        c.setNomeCargo(TFnomeCargo.getText());
        c.setSalario(Float.parseFloat(TFsalario.getText()));
        return c;
    }
}
