/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

/**
 *
 * @author r4f4s
 */
public class CadastroFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBdataAdmissao = new javax.swing.JLabel();
        LBpessoa = new javax.swing.JLabel();
        LBcargo = new javax.swing.JLabel();
        LBlogin = new javax.swing.JLabel();
        LBdescricao = new javax.swing.JLabel();
        LBdatademissao = new javax.swing.JLabel();
        TFpessoa = new javax.swing.JTextField();
        TFcargo = new javax.swing.JTextField();
        TFlogin = new javax.swing.JTextField();
        TFdescricao = new javax.swing.JTextField();
        FTFdataDemissao = new javax.swing.JFormattedTextField();
        FTFdataAdmissao = new javax.swing.JFormattedTextField();

        LBdataAdmissao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdataAdmissao.setText("Data de Admissão:");

        LBpessoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBpessoa.setText("Pessoa:");

        LBcargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcargo.setText("Cargo:");

        LBlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBlogin.setText("Login:");

        LBdescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdescricao.setText("Descrição");

        LBdatademissao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdatademissao.setText("Data de Demissão:");

        FTFdataDemissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FTFdataDemissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFdataDemissaoActionPerformed(evt);
            }
        });

        FTFdataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FTFdataAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFdataAdmissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LBpessoa)
                                .addGap(18, 18, 18)
                                .addComponent(TFpessoa))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LBcargo)
                                .addGap(25, 25, 25)
                                .addComponent(TFcargo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBlogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBdescricao)
                                .addGap(18, 18, 18)
                                .addComponent(TFdescricao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBdatademissao)
                                .addGap(18, 18, 18)
                                .addComponent(FTFdataDemissao))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(LBdataAdmissao)
                        .addGap(18, 18, 18)
                        .addComponent(FTFdataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(283, 283, 283))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBpessoa)
                    .addComponent(TFpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBcargo)
                    .addComponent(LBlogin)
                    .addComponent(TFcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBdescricao)
                    .addComponent(TFdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBdataAdmissao)
                    .addComponent(FTFdataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBdatademissao)
                    .addComponent(FTFdataDemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FTFdataDemissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFdataDemissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTFdataDemissaoActionPerformed

    private void FTFdataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFdataAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTFdataAdmissaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FTFdataAdmissao;
    private javax.swing.JFormattedTextField FTFdataDemissao;
    private javax.swing.JLabel LBcargo;
    private javax.swing.JLabel LBdataAdmissao;
    private javax.swing.JLabel LBdatademissao;
    private javax.swing.JLabel LBdescricao;
    private javax.swing.JLabel LBlogin;
    private javax.swing.JLabel LBpessoa;
    private javax.swing.JTextField TFcargo;
    private javax.swing.JTextField TFdescricao;
    private javax.swing.JTextField TFlogin;
    private javax.swing.JTextField TFpessoa;
    // End of variables declaration//GEN-END:variables
}
