/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Entidade.DAO;
import Entidade.EntidadesBanco.Cliente;
import Entidade.EntidadesBanco.Funcionario;
import Entidade.EntidadesBanco.Produto;
import Entidade.EntidadesBanco.Venda;
import Interfaces.TemplatePainelCadastro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author r4f4s
 */
public class CadastroVenda extends TemplatePainelCadastro {

    /**
     * Creates new form CadastroVenda
     */
    public CadastroVenda() {
        initComponents();
        CBcliente.setModel(new DefaultComboBoxModel(DAO.listaNative(Cliente.class).toArray()));
        CBfuncionario.setModel(new DefaultComboBoxModel(DAO.listaNative(Funcionario.class).toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBdata = new javax.swing.JLabel();
        LBcliente = new javax.swing.JLabel();
        LBfuncionario = new javax.swing.JLabel();
        LBnotaFiscal = new javax.swing.JLabel();
        FTFdata = new javax.swing.JFormattedTextField();
        TFnotaFiscal = new javax.swing.JTextField();
        LBvalor = new javax.swing.JLabel();
        LBvalorVendaDinamico = new javax.swing.JLabel();
        CBcliente = new javax.swing.JComboBox<>();
        CBfuncionario = new javax.swing.JComboBox<>();

        LBdata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBdata.setText("Data:");

        LBcliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBcliente.setText("Cliente:");

        LBfuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBfuncionario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBfuncionario.setText("Funcionário:");

        LBnotaFiscal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBnotaFiscal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBnotaFiscal.setText("Nota Fiscal:");

        try {
            FTFdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LBvalor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBvalor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBvalor.setText("Valor:");

        LBvalorVendaDinamico.setBackground(new java.awt.Color(204, 255, 204));
        LBvalorVendaDinamico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBvalorVendaDinamico.setForeground(new java.awt.Color(0, 0, 204));
        LBvalorVendaDinamico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBvalorVendaDinamico.setText("0");

        CBcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBfuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBcliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBcliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBfuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBfuncionario, 0, 351, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBnotaFiscal)
                        .addGap(18, 18, 18)
                        .addComponent(TFnotaFiscal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBdata)
                        .addGap(18, 18, 18)
                        .addComponent(FTFdata, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LBvalor)
                        .addGap(18, 18, 18)
                        .addComponent(LBvalorVendaDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBcliente)
                    .addComponent(CBcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBdata)
                    .addComponent(FTFdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBfuncionario)
                    .addComponent(CBfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBnotaFiscal)
                            .addComponent(TFnotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBvalor)
                            .addComponent(LBvalorVendaDinamico))
                        .addGap(22, 22, 22))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBcliente;
    private javax.swing.JComboBox<String> CBfuncionario;
    private javax.swing.JFormattedTextField FTFdata;
    private javax.swing.JLabel LBcliente;
    private javax.swing.JLabel LBdata;
    private javax.swing.JLabel LBfuncionario;
    private javax.swing.JLabel LBnotaFiscal;
    private javax.swing.JLabel LBvalor;
    private javax.swing.JLabel LBvalorVendaDinamico;
    private javax.swing.JTextField TFnotaFiscal;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        Venda v = new Venda();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        v.setCliente((Cliente) CBcliente.getSelectedItem());        
        try {
            v.setDataVenda(sdf.parse(FTFdata.getText()));// precisa fazer o role do simpledate format esqueci como faz
        } catch (ParseException ex) {
            Logger.getLogger(CadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        v.setFuncionario((Funcionario) CBfuncionario.getSelectedItem());
        v.setNotaFiscal(TFnotaFiscal.getText());
        v.setValorVenda(Float.parseFloat(LBvalor.getText()));
        return v;
    }

    @Override
    public Object getObjeto(Object o) {
        Venda v;
        if(o == null){
            v = new Venda();

        } else {
            v = (Venda) o;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        v.setCliente((Cliente) CBcliente.getSelectedItem());        
        try {
            v.setDataVenda(sdf.parse(FTFdata.getText()));// precisa fazer o role do simpledate format esqueci como faz
        } catch (ParseException ex) {
            Logger.getLogger(CadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        v.setFuncionario((Funcionario) CBfuncionario.getSelectedItem());
        v.setNotaFiscal(TFnotaFiscal.getText());
        v.setValorVenda(Float.parseFloat(LBvalor.getText()));
        return v;
    }

    @Override
    public void preencherCampos(Object o) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if(o == null){
            TFnotaFiscal.setText("");
            FTFdata.setText("");
            CBcliente.setSelectedItem(null);
            CBfuncionario.setSelectedItem(null);
        }else{
            Venda v = (Venda) o;
            TFnotaFiscal.setText(v.getNotaFiscal());
            FTFdata.setText(sdf.format(v.getDataVenda()));
            CBcliente.setSelectedItem(v.getCliente());
            CBfuncionario.setSelectedItem(v.getFuncionario());
        }
    }
}
