/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Entidade.DAO;
import Entidade.EntidadesBanco.ItemCompra;
import Entidade.EntidadesBanco.ItemVenda;
import Entidade.EntidadesBanco.Produto;
import Interfaces.TemplateLista;
import Interfaces.TemplatePainelCadastro;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author r4f4s
 */
public class CadastroItemVenda extends TemplatePainelCadastro {

    /**
     * Creates new form ItemVenda
     */
    public CadastroItemVenda() {
        initComponents();
        try {
            iv = ItemVenda.class.newInstance(); //caso nao funcione, mudar para class.getdeclaredconstructor().newinstance()
        } catch (InstantiationException ex) {
            Logger.getLogger(CadastroItemVenda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(CadastroItemVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBproduto = new javax.swing.JLabel();
        SPitemVenda = new javax.swing.JScrollPane();
        JTItemVenda = new javax.swing.JTable();
        LBquantidade = new javax.swing.JLabel();
        TFvalor = new javax.swing.JTextField();
        LBValor = new javax.swing.JLabel();
        TFquantidade = new javax.swing.JTextField();
        CBproduto = new javax.swing.JComboBox<>();

        LBproduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBproduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBproduto.setText("Produto:");

        JTItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPitemVenda.setViewportView(JTItemVenda);

        LBquantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBquantidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBquantidade.setText("Quantidade:");

        TFvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFvalorActionPerformed(evt);
            }
        });

        LBValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBValor.setText("Valor:");

        TFquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFquantidadeActionPerformed(evt);
            }
        });

        CBproduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPitemVenda)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBproduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBValor)
                        .addGap(18, 18, 18)
                        .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LBquantidade)
                        .addGap(18, 18, 18)
                        .addComponent(TFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBproduto)
                    .addComponent(LBquantidade)
                    .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBValor)
                    .addComponent(CBproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(SPitemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFvalorActionPerformed

    private void TFquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFquantidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBproduto;
    private javax.swing.JTable JTItemVenda;
    private javax.swing.JLabel LBValor;
    private javax.swing.JLabel LBproduto;
    private javax.swing.JLabel LBquantidade;
    private javax.swing.JScrollPane SPitemVenda;
    private javax.swing.JTextField TFquantidade;
    private javax.swing.JTextField TFvalor;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        ItemVenda iv = new ItemVenda();
        iv.setProduto((Produto) CBproduto.getSelectedItem());
        iv.setQuantidade(Integer.parseInt(TFquantidade.getText()));
        iv.setValor(Float.parseFloat(TFvalor.getText()));
        iv.setVenda(null);//descobrir como colocar a venda selecionada aqui dentro
        return iv;
        
    }
    
    private List<TemplateLista> lista;
    private ItemVenda iv;
    
    public void atualizaTabela() {
        lista = DAO.listaNative(ItemVenda.class);
   
        Object[][] dados= new Object[lista.size()][iv.getTitulos().length];
        
        for (int i = 0; i < lista.size(); i++) {
            dados[i]=lista.get(i).getDados();
        }
        
        JTItemVenda.setModel(new DefaultTableModel(dados,iv.getTitulos()));
    }
}
