/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Entidade.EntidadesBanco.Login;
import Interfaces.TemplatePainelCadastro;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastroLogin extends TemplatePainelCadastro {

    /**
     * Creates new form CadastroLogin
     */
    public CadastroLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBlogin = new javax.swing.JLabel();
        TFlogin = new javax.swing.JTextField();
        LBsenha = new javax.swing.JLabel();
        LBconfirmaSenha = new javax.swing.JLabel();
        PFsenha = new javax.swing.JPasswordField();
        PFconfirmaSenha = new javax.swing.JPasswordField();

        LBlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBlogin.setText("Login:");

        TFlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFloginActionPerformed(evt);
            }
        });

        LBsenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBsenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBsenha.setText("Senha");

        LBconfirmaSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBconfirmaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBconfirmaSenha.setText("Confirme a Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(LBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(371, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LBsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(413, 413, 413))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TFlogin)
                                .addComponent(LBconfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                            .addComponent(PFconfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(362, 362, 362))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(LBlogin)
                .addGap(26, 26, 26)
                .addComponent(TFlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LBsenha)
                .addGap(18, 18, 18)
                .addComponent(PFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(LBconfirmaSenha)
                .addGap(27, 27, 27)
                .addComponent(PFconfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFloginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBconfirmaSenha;
    private javax.swing.JLabel LBlogin;
    private javax.swing.JLabel LBsenha;
    private javax.swing.JPasswordField PFconfirmaSenha;
    private javax.swing.JPasswordField PFsenha;
    private javax.swing.JTextField TFlogin;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        Login l = new Login();
        boolean err = false;
        l.setUsuario(TFlogin.getText());
        if (String.valueOf(PFconfirmaSenha.getPassword()).equals(String.valueOf(PFsenha.getPassword()))) {
            l.setSenha(String.valueOf(PFsenha.getPassword()));
            // getpassword retorna um vetor de char, ai precisa chamar essa funcao para converter para string
        } else {
            JOptionPane.showMessageDialog(null, "As senhas nao coincidem!!");
            err = true;
        }
        if (err == false){
            return l;
        } else {
            return null; // depois vai precisar de um verificador para ver se o objeto é nulo antes de tentar salvar ele
        }
    }
}
