/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

/**
 *
 * @author r4f4s
 */
public class CadastroDespesa extends javax.swing.JPanel {

    /**
     * Creates new form CadastroDespesa
     */
    public CadastroDespesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBnome = new javax.swing.JLabel();
        LBcategoria = new javax.swing.JLabel();
        LBdataVencimento = new javax.swing.JLabel();
        LBpago = new javax.swing.JLabel();
        TFcargo = new javax.swing.JTextField();
        TFnome = new javax.swing.JTextField();
        CBpago = new javax.swing.JCheckBox();
        FTFvencimento = new javax.swing.JFormattedTextField();
        LBvalor = new javax.swing.JLabel();
        TFvalor = new javax.swing.JTextField();

        LBnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBnome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBnome.setText("Nome:");

        LBcategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBcategoria.setText("Categoria:");

        LBdataVencimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdataVencimento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBdataVencimento.setText("Data de Vencimento:");

        LBpago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBpago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBpago.setText("Pago:");

        CBpago.setText("Sim");

        FTFvencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FTFvencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFvencimentoActionPerformed(evt);
            }
        });

        LBvalor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBvalor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBvalor.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBpago)
                        .addGap(45, 45, 45)
                        .addComponent(CBpago, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBcategoria)
                        .addGap(18, 18, 18)
                        .addComponent(TFcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(LBdataVencimento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FTFvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LBnome)
                                .addComponent(LBvalor))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBcategoria)
                    .addComponent(TFcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBnome)
                    .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBvalor))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBpago)
                    .addComponent(CBpago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTFvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBdataVencimento))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FTFvencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFvencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTFvencimentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBpago;
    private javax.swing.JFormattedTextField FTFvencimento;
    private javax.swing.JLabel LBcategoria;
    private javax.swing.JLabel LBdataVencimento;
    private javax.swing.JLabel LBnome;
    private javax.swing.JLabel LBpago;
    private javax.swing.JLabel LBvalor;
    private javax.swing.JTextField TFcargo;
    private javax.swing.JTextField TFnome;
    private javax.swing.JTextField TFvalor;
    // End of variables declaration//GEN-END:variables
}
