/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Interfaces.TemplatePainelCadastro;

/**
 *
 * @author r4f4s
 */
public class CadastroProdutos extends TemplatePainelCadastro {

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBnome = new javax.swing.JLabel();
        LBvalor = new javax.swing.JLabel();
        LBtamanho = new javax.swing.JLabel();
        LBmarca = new javax.swing.JLabel();
        LBcor = new javax.swing.JLabel();
        LBsexo = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        TFtamanho = new javax.swing.JTextField();
        TFmarca = new javax.swing.JTextField();
        TFvalor = new javax.swing.JTextField();
        TFcor = new javax.swing.JTextField();
        RBsexoMasculino = new javax.swing.JRadioButton();
        RBsexoFeminino = new javax.swing.JRadioButton();

        LBnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBnome.setText("Nome:");

        LBvalor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBvalor.setText("Valor:");

        LBtamanho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBtamanho.setText("Tamanho:");

        LBmarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBmarca.setText("Marca:");

        LBcor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcor.setText("Cor:");

        LBsexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBsexo.setText("Sexo:");

        RBsexoMasculino.setText("Masculino");

        RBsexoFeminino.setText("Feminino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBsexo)
                        .addGap(18, 18, 18)
                        .addComponent(RBsexoMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(RBsexoFeminino))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LBnome)
                            .addGap(27, 27, 27)
                            .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LBtamanho)
                                    .addGap(18, 18, 18)
                                    .addComponent(TFtamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBmarca))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LBvalor)
                                    .addGap(18, 18, 18)
                                    .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(LBcor)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFmarca)
                                .addComponent(TFcor)))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBnome)
                    .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBtamanho)
                    .addComponent(TFtamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBmarca)
                    .addComponent(TFmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBvalor)
                        .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBcor)
                        .addComponent(TFcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBsexo)
                    .addComponent(RBsexoMasculino)
                    .addComponent(RBsexoFeminino))
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBcor;
    private javax.swing.JLabel LBmarca;
    private javax.swing.JLabel LBnome;
    private javax.swing.JLabel LBsexo;
    private javax.swing.JLabel LBtamanho;
    private javax.swing.JLabel LBvalor;
    private javax.swing.JRadioButton RBsexoFeminino;
    private javax.swing.JRadioButton RBsexoMasculino;
    private javax.swing.JTextField TFcor;
    private javax.swing.JTextField TFmarca;
    private javax.swing.JTextField TFnome;
    private javax.swing.JTextField TFtamanho;
    private javax.swing.JTextField TFvalor;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
