/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

/**
 *
 * @author r4f4s
 */
public class CadastroPessoa extends javax.swing.JPanel {

    /**
     * Creates new form CadastroPessoa
     */
    public CadastroPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        LBnome = new javax.swing.JLabel();
        LBsexo = new javax.swing.JLabel();
        LBcpf = new javax.swing.JLabel();
        LBrg = new javax.swing.JLabel();
        LBdataNascimento = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        TFcpf = new javax.swing.JTextField();
        TFrg = new javax.swing.JTextField();
        FTFdataNascimento = new javax.swing.JFormattedTextField();
        RBsexoMasculino = new javax.swing.JRadioButton();
        RBsexoFeminino = new javax.swing.JRadioButton();
        LBendereco = new javax.swing.JLabel();
        TFendereco = new javax.swing.JTextField();

        LBnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBnome.setText("Nome:");

        LBsexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBsexo.setText("Sexo:");

        LBcpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcpf.setText("CPF:");

        LBrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBrg.setText("RG:");

        LBdataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBdataNascimento.setText("Data Nascimento:");

        FTFdataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        RBsexoMasculino.setText("Masculino");

        RBsexoFeminino.setText("Feminino");

        LBendereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBendereco.setText("Endereço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBendereco)
                        .addGap(18, 18, 18)
                        .addComponent(TFendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LBcpf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LBdataNascimento)
                            .addGap(18, 18, 18)
                            .addComponent(FTFdataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LBnome)
                            .addGap(18, 18, 18)
                            .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBsexo)
                                .addGap(18, 18, 18)
                                .addComponent(RBsexoMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(RBsexoFeminino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBrg)
                                .addGap(18, 18, 18)
                                .addComponent(TFrg, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBnome)
                    .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBcpf)
                    .addComponent(TFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBrg)
                    .addComponent(TFrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBdataNascimento)
                    .addComponent(LBsexo)
                    .addComponent(FTFdataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBsexoMasculino)
                    .addComponent(RBsexoFeminino))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBendereco)
                    .addComponent(TFendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FTFdataNascimento;
    private javax.swing.JLabel LBcpf;
    private javax.swing.JLabel LBdataNascimento;
    private javax.swing.JLabel LBendereco;
    private javax.swing.JLabel LBnome;
    private javax.swing.JLabel LBrg;
    private javax.swing.JLabel LBsexo;
    private javax.swing.JRadioButton RBsexoFeminino;
    private javax.swing.JRadioButton RBsexoMasculino;
    private javax.swing.JTextField TFcpf;
    private javax.swing.JTextField TFendereco;
    private javax.swing.JTextField TFnome;
    private javax.swing.JTextField TFrg;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
