/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Entidade.DAO;
import Entidade.EntidadesBanco.Gerente;
import Entidade.EntidadesBanco.Login;
import Entidade.EntidadesBanco.Pessoa;
import Interfaces.TemplatePainelCadastro;
import Telas.Cadastro;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author r4f4s
 */
public class CadastroGerente extends TemplatePainelCadastro {
    private boolean check = false;
    /**
     * Creates new form CadastroGerente
     */
    public CadastroGerente() {
        initComponents();
        CBlogin.setModel(new DefaultComboBoxModel(DAO.listaNative(Login.class).toArray()));
        CBpessoa.setModel(new DefaultComboBoxModel(DAO.listaNative(Pessoa.class).toArray()));
        //adicionando novo no CB
        CBlogin.addItem("novo");// colar no resto dos construtores que possuem combobox
        CBpessoa.addItem("novo");// colar no resto dos construtores que possuem combobox
        check = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBlogin = new javax.swing.JLabel();
        LBpessoa1 = new javax.swing.JLabel();
        CBpessoa = new javax.swing.JComboBox<>();
        CBlogin = new javax.swing.JComboBox<>();

        LBlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBlogin.setText("Login:");

        LBpessoa1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBpessoa1.setText("Pessoa:");

        CBpessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBpessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBpessoaItemStateChanged(evt);
            }
        });

        CBlogin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBlogin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBloginItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBpessoa1)
                    .addComponent(LBlogin))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CBpessoa, 0, 222, Short.MAX_VALUE)
                    .addComponent(CBlogin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBpessoa1)
                    .addComponent(CBpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBlogin)
                    .addComponent(CBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CBpessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBpessoaItemStateChanged
        if("novo".equals(CBpessoa.getSelectedItem()+"") && check == true){
            CadastroPessoa CP;
            new Cadastro(null, true, CP = new CadastroPessoa()).setVisible(true);
            CBpessoa.setModel(new DefaultComboBoxModel(DAO.listaNative(Pessoa.class).toArray()));
            CBpessoa.setSelectedItem(CP.getObjeto(null));
            check = false;
            CBpessoa.addItem("novo");
            check = true;
        }
    }//GEN-LAST:event_CBpessoaItemStateChanged

    private void CBloginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBloginItemStateChanged
        if("novo".equals(CBlogin.getSelectedItem()+"") && check == true){
            CadastroLogin CL;
            new Cadastro(null, true, CL = new CadastroLogin()).setVisible(true);
            CBlogin.setModel(new DefaultComboBoxModel(DAO.listaNative(Login.class).toArray()));
            CBlogin.setSelectedItem(CL.getObjeto(null));
            check = false;
            CBlogin.addItem("novo");
            check = true;
        }
    }//GEN-LAST:event_CBloginItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBlogin;
    private javax.swing.JComboBox<String> CBpessoa;
    private javax.swing.JLabel LBlogin;
    private javax.swing.JLabel LBpessoa1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        Gerente g = new Gerente();
        g.setLogin((Login) CBlogin.getSelectedItem());
        g.setPessoa((Pessoa) CBpessoa.getSelectedItem());
        return g;
        
    }

    @Override
    public Object getObjeto(Object o) {
        Gerente g;
        if(o == null){
            g = new Gerente();

        } else {
            g = (Gerente) o;
        }
        g.setLogin((Login) CBlogin.getSelectedItem());
        g.setPessoa((Pessoa) CBpessoa.getSelectedItem());
        return g;
    }

    @Override
    public void preencherCampos(Object o) {
        if(o == null){
            CBlogin.setSelectedItem(null);
            CBpessoa.setSelectedItem(null);
        } else {
            Gerente g = (Gerente) o;
            CBlogin.setSelectedItem(g.getLogin());
            CBpessoa.setSelectedItem(g.getPessoa());
        }
    }
}
