/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Entidade.DAO;
import Entidade.EntidadesBanco.Endereco;
import Entidade.EntidadesBanco.Fornecedor;
import Entidade.EntidadesBanco.Pessoa;
import Entidade.EntidadesBanco.Produto;
import Interfaces.TemplatePainelCadastro;
import Telas.Cadastro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author r4f4s
 */
public class CadastroFornecedor extends TemplatePainelCadastro {
    private boolean check = false;
    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
        CBendereco.setModel(new DefaultComboBoxModel(DAO.listaNative(Endereco.class).toArray()));
        CBendereco.addItem("novo");// colar no resto dos construtores que possuem combobox
        check = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBnome = new javax.swing.JLabel();
        LBcnpj = new javax.swing.JLabel();
        LBendereco = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        TFcnpj = new javax.swing.JTextField();
        CBendereco = new javax.swing.JComboBox<>();

        LBnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBnome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBnome.setText("Nome:");

        LBcnpj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcnpj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBcnpj.setText("CNPJ:");

        LBendereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBendereco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBendereco.setText("Endereco:");

        CBendereco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBendereco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBenderecoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBnome)
                    .addComponent(LBcnpj))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBendereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBnome)
                    .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBcnpj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBendereco)
                        .addComponent(CBendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CBenderecoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBenderecoItemStateChanged
        if("novo".equals(CBendereco.getSelectedItem()+"") && check == true){
            CadastroEndereco CE;
            new Cadastro(null, true, CE = new CadastroEndereco()).setVisible(true);
            CBendereco.getModel().setSelectedItem(CE.getObjeto(null));
        }
    }//GEN-LAST:event_CBenderecoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBendereco;
    private javax.swing.JLabel LBcnpj;
    private javax.swing.JLabel LBendereco;
    private javax.swing.JLabel LBnome;
    private javax.swing.JTextField TFcnpj;
    private javax.swing.JTextField TFnome;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        Fornecedor f = new Fornecedor();
        f.setCpnj(TFcnpj.getText());
        f.setEndereco((Endereco) CBendereco.getSelectedItem());
        f.setNomeFornecedor(TFnome.getText());
        return f;
    }

    @Override
    public Object getObjeto(Object o) {
        Fornecedor f;
        if(o == null){
            f = new Fornecedor();

        } else {
            f = (Fornecedor) o;
        }
        //preenchendo o objeto para salvar, daqui pra baixo voce exclui oq tem e copia tudo do getobjeto() la em cima, tirando
        // a primeira linha q é a declaracao
        f.setCpnj(TFcnpj.getText());
        f.setEndereco((Endereco) CBendereco.getSelectedItem());
        f.setNomeFornecedor(TFnome.getText());
        return f;
    }

    @Override
    public void preencherCampos(Object o) { 
        //aqui é onde vai preencher os campos da tela como vazios, se tiver clicado em salvar
        //ou com os dados do objeto, se tiver clicado em editar
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // se houver algum campo de data isso é necessario
        if(o == null){
            //setando os campos como vazio quando tiver clicado em novo la no listagem
            TFnome.setText("");
            TFcnpj.setText("");
            CBendereco.setSelectedItem(null);
        }else{
            Fornecedor f = (Fornecedor) o; // declara o objeto
            TFnome.setText(f.getNomeFornecedor()); // setando campo de texto, padrao do padrao
            TFcnpj.setText(f.getCpnj());
            CBendereco.setSelectedItem(f.getEndereco());
        }
    }
}
