/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Interfaces.TemplatePainelCadastro;

/**
 *
 * @author r4f4s
 */
public class CadastroEndereco extends TemplatePainelCadastro {

    /**
     * Creates new form CadastroEndereco
     */
    public CadastroEndereco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBcidade = new javax.swing.JLabel();
        LBrua = new javax.swing.JLabel();
        LBestado = new javax.swing.JLabel();
        LBbairro = new javax.swing.JLabel();
        LBnumero = new javax.swing.JLabel();
        LBcomplemento = new javax.swing.JLabel();
        LBcep = new javax.swing.JLabel();
        TFcidade = new javax.swing.JTextField();
        TFestado = new javax.swing.JTextField();
        TFnumero = new javax.swing.JTextField();
        TFbairro = new javax.swing.JTextField();
        TFrua = new javax.swing.JTextField();
        TFcep = new javax.swing.JTextField();
        SPcomplemento = new javax.swing.JScrollPane();
        TAcomplemento = new javax.swing.JTextArea();

        LBcidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBcidade.setText("Cidade:");

        LBrua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBrua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBrua.setText("Rua:");

        LBestado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBestado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBestado.setText("Estado:");

        LBbairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBbairro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBbairro.setText("Bairro:");

        LBnumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBnumero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBnumero.setText("Numero:");

        LBcomplemento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcomplemento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBcomplemento.setText("Complemento:");

        LBcep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBcep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBcep.setText("CEP:");

        TAcomplemento.setColumns(20);
        TAcomplemento.setRows(5);
        SPcomplemento.setViewportView(TAcomplemento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBcomplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SPcomplemento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LBcidade)
                                .addComponent(LBbairro)
                                .addComponent(LBrua))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(TFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBnumero)
                                    .addGap(18, 18, 18)
                                    .addComponent(TFnumero))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(TFcidade)
                                            .addGap(18, 18, 18)
                                            .addComponent(LBestado)
                                            .addGap(18, 18, 18)
                                            .addComponent(TFestado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(TFrua, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(LBcep)
                                            .addGap(18, 18, 18)
                                            .addComponent(TFcep, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBcidade)
                    .addComponent(LBestado)
                    .addComponent(TFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBbairro)
                    .addComponent(TFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBnumero)
                    .addComponent(TFnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBrua)
                    .addComponent(TFrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBcep)
                    .addComponent(TFcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(LBcomplemento)
                .addGap(18, 18, 18)
                .addComponent(SPcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBbairro;
    private javax.swing.JLabel LBcep;
    private javax.swing.JLabel LBcidade;
    private javax.swing.JLabel LBcomplemento;
    private javax.swing.JLabel LBestado;
    private javax.swing.JLabel LBnumero;
    private javax.swing.JLabel LBrua;
    private javax.swing.JScrollPane SPcomplemento;
    private javax.swing.JTextArea TAcomplemento;
    private javax.swing.JTextField TFbairro;
    private javax.swing.JTextField TFcep;
    private javax.swing.JTextField TFcidade;
    private javax.swing.JTextField TFestado;
    private javax.swing.JTextField TFnumero;
    private javax.swing.JTextField TFrua;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
