/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Interfaces.TemplatePainelCadastro;

/**
 *
 * @author r4f4s
 */
public class ItemCompra extends TemplatePainelCadastro {

    /**
     * Creates new form ItemCompra
     */
    public ItemCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBproduto = new javax.swing.JLabel();
        LBValor = new javax.swing.JLabel();
        TFvalor = new javax.swing.JTextField();
        LBquantidade = new javax.swing.JLabel();
        TFquantidade = new javax.swing.JTextField();
        SPitemCompra = new javax.swing.JScrollPane();
        TableItemCompra = new javax.swing.JTable();
        CBproduto = new javax.swing.JComboBox<>();

        LBproduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBproduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBproduto.setText("Produto:");

        LBValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBValor.setText("Valor:");

        TFvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFvalorActionPerformed(evt);
            }
        });

        LBquantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBquantidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBquantidade.setText("Quantidade:");

        TFquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFquantidadeActionPerformed(evt);
            }
        });

        TableItemCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPitemCompra.setViewportView(TableItemCompra);

        CBproduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPitemCompra)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBproduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBValor)
                        .addGap(18, 18, 18)
                        .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LBquantidade)
                        .addGap(18, 18, 18)
                        .addComponent(TFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBproduto)
                    .addComponent(LBquantidade)
                    .addComponent(TFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBValor)
                    .addComponent(CBproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SPitemCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFvalorActionPerformed

    private void TFquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFquantidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBproduto;
    private javax.swing.JLabel LBValor;
    private javax.swing.JLabel LBproduto;
    private javax.swing.JLabel LBquantidade;
    private javax.swing.JScrollPane SPitemCompra;
    private javax.swing.JTextField TFquantidade;
    private javax.swing.JTextField TFvalor;
    private javax.swing.JTable TableItemCompra;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjeto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
